### ISSUE TITLE
please delete this bad report.

### ISSUE THREAD

**Issue by kreezxil** [way2muchnoise/ZenScript-Highlighter-Atom#4]
Something broke in the latest Atom, it says I need the NPM CLI, i have it, but Atom doesn't seem to care. Any ideas?

```
Installing “ZenScript@0.2.5” failed.Hide output…
node:internal/modules/cjs/loader:478
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/npm-cli' is not defined by "exports" in /usr/lib/node_modules/npm/package.json
    at new NodeError (node:internal/errors:329:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:337:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:562:3)
    at resolveExports (node:internal/modules/cjs/loader:472:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:512:31)
    at Function.node_module._findPath (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:141:32)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:909:27)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at new Install (/usr/lib/node_modules/atom-package-manager/lib/install.js:53:34)
    at Object.run (/usr/lib/node_modules/atom-package-manager/lib/apm-cli.js:240:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
Atom version: 1.54.0

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.19-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.5 GiB of RAM
Graphics Processor: GeForce GTX 750 Ti/PCIe/SSE2
```

**Comment by kreezxil** [comment]
darn i did not.

**Comment by kreezxil** [comment]
needed to explictly do
```
npm install npm-cli
```
